services:
  - type: web
    name: bumpy
    env: python
    buildCommand: pip install -r flask_requirements.txt
    startCommand: python app_direct.py
    envVars:
      - key: PYTHONUNBUFFERED
        value: true
      - key: FLASK_ENV
        value: production
    scaling:
      minInstances: 1
      maxInstances: 1
    plan: standard
    healthCheckPath: /health
    disk:
      name: tmpdata
      mountPath: /tmp
      sizeGB: 1 