services:
  - type: web
    name: bumpy
    env: python
    buildCommand: echo "No build needed"
    startCommand: python simple_server.py
    envVars:
      - key: PYTHONUNBUFFERED
        value: true
    scaling:
      minInstances: 1
      maxInstances: 1  # Reduced to 1 to avoid memory issues
    plan: standard
    healthCheckPath: /health
    disk:
      name: tmpdata
      mountPath: /tmp
      sizeGB: 1 