services:
  - type: web
    name: bumpy
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python test_app.py
    envVars:
      - key: FLASK_ENV
        value: production
      - key: PYTHONUNBUFFERED
        value: true
    scaling:
      minInstances: 1
      maxInstances: 1  # Reduced to 1 to avoid memory issues
    plan: standard
    healthCheckPath: /health
    disk:
      name: tmpdata
      mountPath: /tmp
      sizeGB: 1 